### ISSUE TITLE
New examples

### ISSUE THREAD

**Issue by TomDonoghue** [fooof-tools/fooof#226]
New examples that should be added:
- [x] Visualize data components (show different isolated data components) (in #284)
- [x] Line noise and interpolating frequency regions (was done in #203)
- [x] Pulling apart exponent & offset / working with aperiodic parameters (in #284)
- [x] Showing the methods reports (in #284)
- [x] Showing the functionality to export model fit results to dataframes (`data.conversions`) (in #284)
- [x] Add example page adapted from the Developmental Demo (in #286)

**Comment by TomDonoghue** [comment]
These are done and/or in progress in #284 - so I'm going to close this here and any discussion can continue in the PR.
