### ISSUE TITLE
Spinx ToDo

### ISSUE THREAD

**Issue by TomDonoghue** [fooof-tools/fooof#94]
- [x] Change theme: better rendering
- [x] Linking examples from function doc pages (and vice versa)
- [x] Clean up the nb converted scripts
- [x] Fix up the loading of files in the examples scripts

**Comment by TomDonoghue** [comment]
Finished with #123
